
export default async function handler(req, res) {
    // CORS Handling (Allow requests from our frontend)
    res.setHeader('Access-Control-Allow-Credentials', true);
    res.setHeader('Access-Control-Allow-Origin', '*'); // Adjust this for production security
    res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
    res.setHeader(
        'Access-Control-Allow-Headers',
        'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
    );

    // Handle OPTIONS request preflight
    if (req.method === 'OPTIONS') {
        res.status(200).end();
        return;
    }

    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method Not Allowed' });
    }

    const { prompt } = req.body;
    const apiKey = process.env.VITE_NANOBANANA_API_KEY; // Read from Vercel Environment Variables

    if (!apiKey) {
        return res.status(500).json({ error: 'Server Config Error: Missing API Key' });
    }

    try {
        const model = "gemini-2.5-flash-image";
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

        const response = await fetch(url, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                contents: [{
                    parts: [{ text: `Generate a high-quality 2D vector character image. Based on: ${prompt}` }]
                }],
                generationConfig: {
                    temperature: 0.4
                }
            })
        });

        if (!response.ok) {
            const errData = await response.json().catch(() => ({}));
            throw new Error(errData.error?.message || `Gemini API Error: ${response.status}`);
        }

        const data = await response.json();

        // Check for Image in the response
        const candidate = data.candidates?.[0]?.content?.parts?.[0];
        let finalImageUrl = null;

        if (candidate?.inlineData && candidate.inlineData.mimeType.startsWith('image/')) {
            finalImageUrl = `data:${candidate.inlineData.mimeType};base64,${candidate.inlineData.data}`;
        } else if (candidate?.text && candidate.text.startsWith('http')) {
            finalImageUrl = candidate.text;
        }

        if (finalImageUrl) {
            return res.status(200).json({ success: true, imageUrl: finalImageUrl });
        } else {
            return res.status(422).json({ success: false, error: "No image generated by AI." });
        }

    } catch (error) {
        console.error("Vercel Function Error:", error);
        return res.status(500).json({ error: error.message });
    }
}
